### ISSUE TITLE
Cannot install with PHP 5.6 and above...

### ISSUE THREAD

**Issue by prashanthpg** [DoveID/Magento-Ajax-Login#10]
Connect Error is as follows....

CONNECT ERROR: Package community/Youama_Ajaxlogin 2.0.1: requires PHP version >= 5.1.0 and <= 5.5.12 current is: 5.6.11

**Comment by mbegunok** [comment]
Please, help. Have the same issue

**Comment by DoveID** [comment]
New fixed version 2.0.4 is able to download via Magento Connect. Compatibility from PHP 5 up to PHP 7.0.2

**Comment by mbegunok** [comment]
Dear David
I finally  installed your module. but for some reason I still can't
register new account in Google Chrome and Firefox, even in Apple Safari it
works just fine.
Could you give me advise - where to kkot at the issue?
Web site - http://fancynails.ru/
Maxim

2016-01-24 10:55 GMT+03:00 David Belicza <notifications@github.com>:

**Comment by DoveID** [comment]
You should check the difference between your frontend and the official RWD frontend: http://magento.youama.com/.

Or install another version of the module from Magento Connect from Release list manually.

**Comment by mbegunok** [comment]
Dear David
I figure out what is the problem. It could be common problems with using
cloudflare.
They have option - rocket loader which minimize Java Script. After
switching this option off, registration is fine
Rocket Loader™ BETA

Improve load time for pages that include JavaScript.

2016-01-24 13:22 GMT+03:00 David Belicza <notifications@github.com>:
