### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by oucart** [DoveID/Magento-Ajax-Login#11]
hello, i use this plugin , in RWD theme ,I need to click many times before they can pop up。
![c1](https://cloud.githubusercontent.com/assets/4326820/12615685/1d768c64-c542-11e5-8549-8b343921a7e4.png)

![c2](https://cloud.githubusercontent.com/assets/4326820/12615714/4bf7b176-c542-11e5-8485-815a6a556446.png)

my website
http://112.74.135.101/cheeyou/

**Comment by DavidBelicza** [comment]
It is not a Magento site.
