### ISSUE TITLE
PHP 7.2 Compatibility

### ISSUE THREAD

**Issue by scottcdi** [DoveID/Magento-Ajax-Login#15]
Magento just recently announced that they will be openly supporting PHP 7.2 for the magento 1 instance and have also recently just released a patch.

Does anyone know if this plugin will be compatible with PHP 7.2 or if a patch is planning on being developed here as well?

**Comment by DavidBelicza** [comment]
It should work, because it doesn't contain any deprecated language feature. However if it was broken on 7.2 and someone reports the issue I'll gonna fix it.

**Comment by scottcdi** [comment]
Thank you David. Without looking at the source code, I figured much of the same but wanted to double check. Will spin up a dev env with the patch and report back with any issues.
