### ISSUE TITLE
want to login form and register form in popup

### ISSUE THREAD

**Issue by purvi123** [DoveID/Magento-Ajax-Login#6]
Hello,

This extension is very useful for me.but i want login form and register form as popup.

Is it possible?

**Comment by DoveID** [comment]
It is. You can redevelop the javacript what puts form to the header or you can use the older version of this module what shows the login and register forms by a popup window. You can download the older versions from http://www.magentocommerce.com/magento-connect/catalog/product/view/id/16151/s/youama-ajax-login-and-register-7003/

**Comment by purvi123** [comment]
old version demo is not shown.
http://demo.youama.com/cgi-sys/defaultwebpage.cgi
