### ISSUE TITLE
want to login form and register form in popup

### ISSUE THREAD

**Issue by purvi123** [DoveID/Magento-Ajax-Login#7]
old version demo is not shown.
http://demo.youama.com/cgi-sys/defaultwebpage.cgi

**Comment by DoveID** [comment]
Thanks for the reporting. I shut down those demo sites some weeks ago. You can find documentations on youama.com, or you can download the different versions and try them.

**Comment by purvi123** [comment]
ok thanks for your reply.can u please tell me which version you used popup functionality?

**Comment by DoveID** [comment]
The previous version: 1.1.2
