### ISSUE TITLE
email with + sign is not validating

### ISSUE THREAD

**Issue by rkjamvi** [DoveID/Magento-Ajax-Login#9]
Hi,

We are using this plugin for one of our magento store and on login validation, its not validating below email id format:

rizwan+karim@gmail.com

Please advise.

**Comment by DoveID** [comment]
Hello,

This module validates email on two places: backend and frontend. Backend can accept your email, but frontend.

You should rewrite the frontend email filter in module to mach your email rizwan+karim@gmail.com with the pattern at this line: https://github.com/DoveID/Magento-Ajax-Login/blob/master/skin/frontend/base/default/js/youama/ajaxlogin/ajaxlogin.js#L315
